In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("credit_risk_dataset.csv")

In [3]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [4]:
df.shape

(32581, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

In [6]:
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [7]:
df['loan_status'].value_counts()

loan_status
0    25473
1     7108
Name: count, dtype: int64

In [9]:
df[df['person_emp_length'].isnull()].head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
105,22,12600,MORTGAGE,NaN,PERSONAL,A,2000,5.42,1,0.16,N,4
222,24,185000,MORTGAGE,NaN,EDUCATION,B,35000,12.42,0,0.19,N,2
379,24,16800,MORTGAGE,NaN,DEBTCONSOLIDATION,A,3900,NaN,1,0.23,N,3
407,25,52000,RENT,NaN,PERSONAL,B,24000,10.74,1,0.46,N,2
408,22,17352,MORTGAGE,NaN,EDUCATION,C,2250,15.27,0,0.13,Y,3

In [10]:
df[df['loan_int_rate'].isnull()].head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
39,23,71500,RENT,3.0,DEBTCONSOLIDATION,D,30000,NaN,1,0.42,N,4
50,24,78000,RENT,4.0,DEBTCONSOLIDATION,D,30000,NaN,1,0.38,Y,4
57,23,277000,OWN,3.0,PERSONAL,A,35000,NaN,0,0.13,N,4
59,24,12000,OWN,2.0,VENTURE,E,1750,NaN,0,0.15,Y,3
62,26,263000,MORTGAGE,0.0,EDUCATION,B,10000,NaN,1,0.04,N,4

In [11]:
df.groupby('loan_grade')['loan_int_rate'].apply(lambda x: x.isnull().sum())

loan_grade
A    1003
B    1056
C     630
D     312
E      83
F      27
G       5
Name: loan_int_rate, dtype: int64

In [13]:
df[['person_emp_length', 'loan_int_rate']].median()

person_emp_length     4.00
loan_int_rate        10.99
dtype: float64

In [14]:
df[['person_emp_length', 'loan_int_rate']].describe()

       person_emp_length  loan_int_rate
count       31686.000000   29465.000000
mean            4.789686      11.011695
std             4.142630       3.240459
min             0.000000       5.420000
25%             2.000000       7.900000
50%             4.000000      10.990000
75%             7.000000      13.470000
max           123.000000      23.220000

In [15]:
df.groupby('loan_grade')['loan_int_rate'].median()

loan_grade
A     7.490
B    10.990
C    13.480
D    15.310
E    16.820
F    18.535
G    20.160
Name: loan_int_rate, dtype: float64

In [16]:
df[df['person_emp_length'] > 50]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
210,21,192000,MORTGAGE,123.0,VENTURE,A,20000,6.54,0,0.10,N,4

In [17]:
df['person_emp_length'].value_counts().sort_index().tail(15)

person_emp_length
21.0     38
22.0     19
23.0     10
24.0     10
25.0      8
26.0      6
27.0      5
28.0      3
29.0      1
30.0      2
31.0      4
34.0      1
38.0      1
41.0      1
123.0     2
Name: count, dtype: int64

In [18]:
df['person_emp_length'] = df['person_emp_length'].replace(123, np.nan)

In [19]:
df['person_emp_length'].isnull().sum()

np.int64(897)

In [21]:
df['person_emp_length'] = df['person_emp_length'].fillna(
    df['person_emp_length'].median())

In [22]:
df['person_emp_length'].isnull().sum()

np.int64(0)

In [24]:
df['loan_int_rate'] = df['loan_int_rate'].fillna(
    df.groupby('loan_grade')['loan_int_rate'].transform('median'))

In [25]:
df['loan_int_rate'].isnull().sum()

np.int64(0)

In [26]:
df.duplicated().sum()

np.int64(165)

In [27]:
df = df.drop_duplicates()

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.shape

(32416, 12)

In [30]:
df['person_age'].describe()

count    32416.000000
mean        27.747008
std          6.354100
min         20.000000
25%         23.000000
50%         26.000000
75%         30.000000
max        144.000000
Name: person_age, dtype: float64

In [31]:
df['person_age'].value_counts().sort_index().tail(15)

person_age
63     3
64     7
65     9
66     9
67     1
69     5
70     7
73     3
76     1
78     1
80     1
84     1
94     1
123    2
144    3
Name: count, dtype: int64

In [39]:
df['person_age'].isnull().sum()

np.int64(0)

In [35]:
df = df.copy()

In [36]:
df['person_age'] = df['person_age'].replace([123, 144], np.nan)

In [38]:
df['person_age'] = df['person_age'].fillna(
    df['person_age'].median()
)

In [41]:
df['person_income'].describe()

count    3.241600e+04
mean     6.609164e+04
std      6.201558e+04
min      4.000000e+03
25%      3.854200e+04
50%      5.500000e+04
75%      7.921800e+04
max      6.000000e+06
Name: person_income, dtype: float64

In [42]:
df['person_income'].value_counts().sort_index().tail(10)

person_income
889000     1
900000     4
948000     1
1200000    3
1362000    1
1440000    1
1782000    1
1900000    1
2039784    1
6000000    1
Name: count, dtype: int64

In [43]:
df.nlargest(10, 'person_income')[
    ['person_age', 'person_income', 'loan_amnt', 'loan_percent_income', 'loan_status']
]

       person_age  person_income  loan_amnt  loan_percent_income  loan_status
32297        26.0        6000000       5000                 0.00            0
30049        42.0        2039784       8450                 0.00            0
32546        60.0        1900000       1500                 0.00            0
32497        63.0        1782000      12025                 0.01            0
31924        44.0        1440000       6400                 0.00            0
31922        47.0        1362000       6600                 0.00            0
17833        32.0        1200000      12000                 0.01            0
29119        36.0        1200000      10000                 0.01            0
29120        40.0        1200000      10000                 0.01            0
17834        34.0         948000       2000                 0.00            0

In [44]:
df['calculated_loan_percent_income'] = (
    df['loan_amnt'] / df['person_income']
)

In [45]:
df[['loan_amnt', 'person_income', 'loan_percent_income',
    'calculated_loan_percent_income']].head(10)

,loan_amnt,person_income,loan_percent_income,calculated_loan_percent_income
0,35000,59000,0.59,0.593220
1,1000,9600,0.10,0.104167
2,5500,9600,0.57,0.572917
3,35000,65500,0.53,0.534351
4,35000,54400,0.55,0.643382
5,2500,9900,0.25,0.252525
6,35000,77100,0.45,0.453956
7,35000,78956,0.44,0.443285
8,35000,83000,0.42,0.421687
9,1600,10000,0.16,0.160000

In [46]:
df.drop(columns=['calculated_loan_percent_income'], inplace=True)

In [47]:
df['loan_status'].mean() * 100

np.float64(21.868830207305034)

In [48]:
default_by_grade = df.groupby('loan_grade')['loan_status'].mean() * 100
default_by_grade.sort_values(ascending=False)

loan_grade
G    98.437500
F    70.539419
E    64.485981
D    59.060773
C    20.751786
B    16.318475
A     9.959824
Name: loan_status, dtype: float64

In [49]:
df['loan_grade'].value_counts().sort_index()

loan_grade
A    10703
B    10387
C     6438
D     3620
E      963
F      241
G       64
Name: count, dtype: int64

In [50]:
default_by_intent = df.groupby('loan_intent')['loan_status'].mean() * 100

default_by_intent.sort_values(ascending=False)

loan_intent
DEBTCONSOLIDATION    28.676045
MEDICAL              26.762661
HOMEIMPROVEMENT      26.154702
PERSONAL             19.898145
EDUCATION            17.251599
VENTURE              14.853925
Name: loan_status, dtype: float64

In [51]:
df['income_group'] = pd.cut(
    df['person_income'],
    bins=[0, 30000, 50000, 75000, 100000, np.inf],
    labels=['Low', 'Lower-Mid', 'Upper-Mid', 'High', 'Very High']
)

default_by_income = df.groupby('income_group', observed=True)['loan_status'].mean() * 100

default_by_income

income_group
Low          45.586268
Lower-Mid    25.659624
Upper-Mid    17.642149
High         11.032105
Very High     9.544262
Name: loan_status, dtype: float64

In [52]:
df['loan_income_group'] = pd.cut(
    df['loan_percent_income'],
    bins=[0, 0.10, 0.20, 0.30, 0.40, 1],
    labels=['0-10%', '10-20%', '20-30%', '30-40%', '40%+']
)

default_by_loan_income = (
    df.groupby('loan_income_group', observed=True)['loan_status'].mean() * 100
)

default_by_loan_income

loan_income_group
0-10%     11.764706
10-20%    15.126261
20-30%    22.016861
30-40%    68.888889
40%+      74.173369
Name: loan_status, dtype: float64

In [53]:
df['loan_income_group'].value_counts().sort_index()

loan_income_group
0-10%     10421
10-20%    11999
20-30%     6168
30-40%     2700
40%+       1119
Name: count, dtype: int64

In [54]:
default_by_history = (
    df.groupby('cb_person_default_on_file')['loan_status'].mean() * 100
)

default_by_history

cb_person_default_on_file
N    18.432886
Y    37.870855
Name: loan_status, dtype: float64

In [55]:
pd.crosstab(
    df['loan_grade'],
    df['cb_person_default_on_file'],
    normalize='index'
) * 100

cb_person_default_on_file           N          Y
loan_grade
A                          100.000000   0.000000
B                          100.000000   0.000000
C                           49.596148  50.403852
D                           48.259669  51.740331
E                           51.817238  48.182762
F                           53.526971  46.473029
G                           43.750000  56.250000

In [56]:
df['risk_segment'] = np.select(
    [
        df['loan_percent_income'] >= 0.30,
        df['loan_percent_income'] >= 0.20
    ],
    [
        'High Risk',
        'Medium Risk'
    ],
    default='Low Risk'
)

In [57]:
df['risk_segment'].value_counts()

risk_segment
Low Risk       21363
Medium Risk     6786
High Risk       4267
Name: count, dtype: int64

In [58]:
default_by_risk = (
    df.groupby('risk_segment', observed=True)['loan_status'].mean() * 100
)

default_by_risk

risk_segment
High Risk      65.573002
Low Risk       13.425081
Medium Risk    20.969643
Name: loan_status, dtype: float64

In [59]:
df.to_csv("credit_risk_cleaned.csv", index=False)

In [60]:
import os

os.path.exists("credit_risk_cleaned.csv")

True